spring:
  profiles:
    active: #spring.profiles.active#
  application:
    name: observation-animaux-marins
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
  datasource:
    url: jdbc:h2:file:./data/bdd
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true